// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BMbNdXNJYfnMeSCS_rNbv0KhEPLu3_g',
    appId: '1:545397305971:web:d9299d5a5667431b5e7006',
    messagingSenderId: '545397305971',
    projectId: 'traitmate-7d324',
    authDomain: 'traitmate-7d324.firebaseapp.com',
    databaseURL: 'https://traitmate-7d324-default-rtdb.firebaseio.com',
    storageBucket: 'traitmate-7d324.appspot.com',
    measurementId: 'G-Y19P31R2XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzTIN8m0J_xO8OsQ2f-jkSwclWA0NFXgQ',
    appId: '1:545397305971:android:f7644292140abad05e7006',
    messagingSenderId: '545397305971',
    projectId: 'traitmate-7d324',
    databaseURL: 'https://traitmate-7d324-default-rtdb.firebaseio.com',
    storageBucket: 'traitmate-7d324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmE4ih27Oz5Ecp0Yz1yZtIOyHJ2hJWtg',
    appId: '1:545397305971:ios:28b76c32c08b9ba25e7006',
    messagingSenderId: '545397305971',
    projectId: 'traitmate-7d324',
    databaseURL: 'https://traitmate-7d324-default-rtdb.firebaseio.com',
    storageBucket: 'traitmate-7d324.appspot.com',
    iosBundleId: 'com.example.traitMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPmE4ih27Oz5Ecp0Yz1yZtIOyHJ2hJWtg',
    appId: '1:545397305971:ios:4afebd1303fb071b5e7006',
    messagingSenderId: '545397305971',
    projectId: 'traitmate-7d324',
    databaseURL: 'https://traitmate-7d324-default-rtdb.firebaseio.com',
    storageBucket: 'traitmate-7d324.appspot.com',
    iosBundleId: 'com.example.traitMate.RunnerTests',
  );
}
